services:
  postgres:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
